fragment page_blogSingle on page_blogSingle_Entry {
  # Entry Data
  ...entry_data
  ...entry_dates
  ...entry_seo @include(if: $fullContent)
  ...entry_prev @include(if: $fullContent)
  ...entry_next @include(if: $fullContent)

  # Author Data
  ...author_data @include(if: $fullContent)

  description @include(if: $fullContent)
  descriptionPlain: description @stripTags
  customTitle
  image @include(if: $fullContent) {
    ...asset_data
    ...asset_transforms
    ...asset_customFields
  }
  contentBuilder @include(if: $fullContent) {
    ...matrix_contentBuilder
  }

  category {
    ...entry_data
  }

  topics {
    ...entry_data
  }
}
