fragment page_workSingle on page_workSingle_Entry {
  # Entry Data
  ...entry_data
  ...entry_dates
  ...entry_seo @include(if: $fullContent)
  ...entry_prev @include(if: $fullContent)
  ...entry_next @include(if: $fullContent)

  # Author Data
  ...author_data @include(if: $fullContent)

  description @include(if: $fullContent)
  descriptionPlain: description @stripTags
  customTitle
  image {
    ...asset_data
    ...asset_transforms
    ...asset_customFields
  }
  images @include(if: $fullContent) {
    ...asset_data
    ...asset_transforms
    ...asset_customFields
  }
  contentBuilderWork @include(if: $fullContent) {
    ...matrix_contentBuilderWork
  }
  colors @include(if: $fullContent) {
    color
  }
  clientWords @include(if: $fullContent)
  projectDescription @include(if: $fullContent)
  projectLink @include(if: $fullContent) {
    ...hyper_data
  }
  workAreas @include(if: $fullContent) {
    ...page_workArea
  }
  workType {
    ...page_workType
  }
  agency {
    ...page_company
  }
  client {
    ...page_company
  }
}
