fragment page_photosSingle on page_photosSingle_Entry {
  # Entry Data
  ...entry_data
  ...entry_dates
  ...entry_seo @include(if: $fullContent)
  ...entry_prev @include(if: $fullContent)
  ...entry_next @include(if: $fullContent)

  # Author Data
  ...author_data @include(if: $fullContent)

  description @include(if: $fullContent)
  descriptionPlain: description @stripTags @include(if: $fullContent)
  customTitle @include(if: $fullContent)
  image {
    ...asset_data
    ...asset_transforms
    ...asset_customFields
  }
  images {
    ...asset_data
    ...asset_transforms
    ...asset_customFields
  }

  previewImages: images (limit: 4, orderBy: "RAND()") {
    ...asset_data
    ...asset_transforms
    ...asset_customFields
  }
}
