/* this file was generated by vite-svg-sprite-wrapper */
export type HeroiconsIcons = 'arrow-left-outline' | 'arrow-right-outline' | 'building-office-outline' | 'calendar-outline' | 'face-smile-outline' | 'folder-open-outline' | 'hand-raised-outline' | 'home-modern-outline' | 'megaphone-outline' | 'tag-outline' | 'user-outline' | 'users-outline'
