/* this file was generated by vite-svg-sprite-wrapper */
export type HeroiconsIcons = 'arrow-left-outline' | 'arrow-right-outline' | 'calendar-outline' | 'face-smile-outline' | 'folder-open-outline' | 'hand-raised-outline' | 'megaphone-outline' | 'tag-outline'
